name: Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast-analysis:
    name: Run SAST Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download SYHUNT Community
        run: |
          wget https://www.syhunt.com/download/syhunt-code-community.tar.gz
          tar -xvzf syhunt-code-community.tar.gz

      - name: Run SYHUNT SAST
        run: |
          ./syhuntcode scan --target ./src --output ./sast-report.html

      - name: Upload SAST Report
        uses: actions/upload-artifact@v3
        with:
          name: sast-report
          path: ./sast-report.html

  dast-analysis:
    name: Run DAST Analysis
    runs-on: ubuntu-latest
    needs: sast-analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: |
          node src/app.js &
          sleep 5

      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          target: 'http://localhost:8080'
          rulesFileName: '.zap/rules.tsv'

      - name: Upload DAST Report
        uses: actions/upload-artifact@v3
        with:
          name: dast-report
          path: owasp-zap-report.html
